type Query {
  hello: String
  customers(limit: Int, offset: Int, q: String): [Customer!]
  customer(id: String!): Customer
  login(username: String!, password: String!): Boolean
}

type Customer {
  id: String!
  name: String!
  contracts: [Contract!]
}

type Contract {
  id: String!
}